import React from 'react'

const Categories = () => {
  return (
    <div>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempore aspernatur porro quas corrupti laudantium saepe, deleniti suscipit praesentium, provident earum non explicabo aut fugiat voluptas amet aperiam dolores hic eveniet velit laboriosam fugit! Natus obcaecati voluptatum, voluptate facere ab quisquam saepe nostrum, minus odio dicta animi! Amet, ipsam quo eius vero in soluta cumque quidem provident doloremque quaerat pariatur hic ut inventore, iusto asperiores labore mollitia aliquam perspiciatis libero. Ullam rerum quibusdam quo totam vel, illo maiores eligendi tempore quis tempora repellendus. Suscipit explicabo aspernatur, rem numquam cupiditate accusantium a necessitatibus velit blanditiis quidem maxime dicta debitis corrupti rerum ex.</p>
      <br />
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempore aspernatur porro quas corrupti laudantium saepe, deleniti suscipit praesentium, provident earum non explicabo aut fugiat voluptas amet aperiam dolores hic eveniet velit laboriosam fugit! Natus obcaecati voluptatum, voluptate facere ab quisquam saepe nostrum, minus odio dicta animi! Amet, ipsam quo eius vero in soluta cumque quidem provident doloremque quaerat pariatur hic ut inventore, iusto asperiores labore mollitia aliquam perspiciatis libero. Ullam rerum quibusdam quo totam vel, illo maiores eligendi tempore quis tempora repellendus. Suscipit explicabo aspernatur, rem numquam cupiditate accusantium a necessitatibus velit blanditiis quidem maxime dicta debitis corrupti rerum ex.</p>
      <br />
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempore aspernatur porro quas corrupti laudantium saepe, deleniti suscipit praesentium, provident earum non explicabo aut fugiat voluptas amet aperiam dolores hic eveniet velit laboriosam fugit! Natus obcaecati voluptatum, voluptate facere ab quisquam saepe nostrum, minus odio dicta animi! Amet, ipsam quo eius vero in soluta cumque quidem provident doloremque quaerat pariatur hic ut inventore, iusto asperiores labore mollitia aliquam perspiciatis libero. Ullam rerum quibusdam quo totam vel, illo maiores eligendi tempore quis tempora repellendus. Suscipit explicabo aspernatur, rem numquam cupiditate accusantium a necessitatibus velit blanditiis quidem maxime dicta debitis corrupti rerum ex.</p>
      <br />
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempore aspernatur porro quas corrupti laudantium saepe, deleniti suscipit praesentium, provident earum non explicabo aut fugiat voluptas amet aperiam dolores hic eveniet velit laboriosam fugit! Natus obcaecati voluptatum, voluptate facere ab quisquam saepe nostrum, minus odio dicta animi! Amet, ipsam quo eius vero in soluta cumque quidem provident doloremque quaerat pariatur hic ut inventore, iusto asperiores labore mollitia aliquam perspiciatis libero. Ullam rerum quibusdam quo totam vel, illo maiores eligendi tempore quis tempora repellendus. Suscipit explicabo aspernatur, rem numquam cupiditate accusantium a necessitatibus velit blanditiis quidem maxime dicta debitis corrupti rerum ex.</p>
      <br />
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempore aspernatur porro quas corrupti laudantium saepe, deleniti suscipit praesentium, provident earum non explicabo aut fugiat voluptas amet aperiam dolores hic eveniet velit laboriosam fugit! Natus obcaecati voluptatum, voluptate facere ab quisquam saepe nostrum, minus odio dicta animi! Amet, ipsam quo eius vero in soluta cumque quidem provident doloremque quaerat pariatur hic ut inventore, iusto asperiores labore mollitia aliquam perspiciatis libero. Ullam rerum quibusdam quo totam vel, illo maiores eligendi tempore quis tempora repellendus. Suscipit explicabo aspernatur, rem numquam cupiditate accusantium a necessitatibus velit blanditiis quidem maxime dicta debitis corrupti rerum ex.</p>
      <br />
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempore aspernatur porro quas corrupti laudantium saepe, deleniti suscipit praesentium, provident earum non explicabo aut fugiat voluptas amet aperiam dolores hic eveniet velit laboriosam fugit! Natus obcaecati voluptatum, voluptate facere ab quisquam saepe nostrum, minus odio dicta animi! Amet, ipsam quo eius vero in soluta cumque quidem provident doloremque quaerat pariatur hic ut inventore, iusto asperiores labore mollitia aliquam perspiciatis libero. Ullam rerum quibusdam quo totam vel, illo maiores eligendi tempore quis tempora repellendus. Suscipit explicabo aspernatur, rem numquam cupiditate accusantium a necessitatibus velit blanditiis quidem maxime dicta debitis corrupti rerum ex.</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempore aspernatur porro quas corrupti laudantium saepe, deleniti suscipit praesentium, provident earum non explicabo aut fugiat voluptas amet aperiam dolores hic eveniet velit laboriosam fugit! Natus obcaecati voluptatum, voluptate facere ab quisquam saepe nostrum, minus odio dicta animi! Amet, ipsam quo eius vero in soluta cumque quidem provident doloremque quaerat pariatur hic ut inventore, iusto asperiores labore mollitia aliquam perspiciatis libero. Ullam rerum quibusdam quo totam vel, illo maiores eligendi tempore quis tempora repellendus. Suscipit explicabo aspernatur, rem numquam cupiditate accusantium a necessitatibus velit blanditiis quidem maxime dicta debitis corrupti rerum ex.</p>
    </div>
  )
}

export default Categories