export {default as Home} from './Home';
export {default as About} from './About'
export {default as Cart} from './Cart'
export {default as Categories} from './Categories/Categories'
export {default as Contact} from './Contact'
export {default as Account} from './Account'
export {default as Settings} from './Settings/Settings'
export { ProductsPage } from './ProductsPage';
export { LoginPage } from './LoginPage/LoginPage';
export { SignUp } from './SignUp/SignUp';
export { Profile } from './Profile/Profile'
export { ErrorPage } from './ErrorPage/ErrorPage';
export { LandingPage } from './LandingPage/LandingPage';