# Generated by Django 4.2.1 on 2023-07-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_banner'),
        ('variations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='variation_option',
            field=models.ManyToManyField(to='variations.variationoptions'),
        ),
    ]
