# Generated by Django 4.2.1 on 2023-07-15 19:36

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productitem_variation_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': '1. Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, upload_to=products.models.upload_product_icon),
        ),
    ]
