# Generated by Django 4.2.1 on 2023-07-18 18:17

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default='/icons/placeholder.jpg', upload_to='categories/'),
        ),
    ]
