# Generated by Django 4.2.1 on 2023-07-18 20:12

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, default='icons/placeholder.jpg', upload_to=products.models.upload_product_icon),
        ),
    ]
