# Generated by Django 4.2.1 on 2023-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
