# Generated by Django 4.2.1 on 2023-08-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_discount_productimage_productitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.PositiveBigIntegerField(verbose_name='discount percentage'),
        ),
    ]
