# Generated by Django 4.2.1 on 2023-08-06 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_discount_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(100, message='max value is 100')], verbose_name='discount percentage'),
        ),
    ]
