# Generated by Django 4.2.1 on 2023-08-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_discount_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
