# Generated by Django 4.2.1 on 2023-11-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_discount_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='ifFeatured',
            field=models.BooleanField(default=False),
        ),
    ]
