# Generated by Django 4.2.1 on 2023-11-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productitem_iffeatured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='ifFeatured',
            new_name='is_featured',
        ),
    ]
