# Generated by Django 4.2.1 on 2023-11-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_iffeatured_productitem_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.productitem'),
        ),
    ]
