# Generated by Django 4.2.1 on 2023-12-03 21:12

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_productimage_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='has_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(upload_to=products.models.upload_product_thumb),
        ),
    ]
