# Generated by Django 4.2.1 on 2023-12-03 21:14

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_productimage_has_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=products.models.upload_product_thumb),
        ),
    ]
