# Generated by Django 4.2.1 on 2023-12-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_is_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
