# Generated by Django 4.2.1 on 2023-12-10 23:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_features_productimage_remove_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='productimage',
            name='remove_background',
            field=models.BooleanField(default=False, help_text='experimental, works with white background'),
        ),
    ]
