# Generated by Django 4.2.1 on 2023-12-10 23:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_product_features_productimage_remove_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
    ]
