# Generated by Django 4.2.1 on 2024-01-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_productitem_detailed_description_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='variation_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
