# Generated by Django 4.2.1 on 2024-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productitem_variation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='variation_name',
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
