# Generated by Django 4.2.1 on 2024-01-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_remove_productitem_variation_name_category_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
