# Generated by Django 4.2.1 on 2024-08-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_rename_product_id_productitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured_product',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='is_featured',
            new_name='is_default',
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='is_featured',
            new_name='is_default',
        ),
    ]
