# Generated by Django 4.2.1 on 2024-09-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_rename_is_featured_product_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
