# Generated by Django 4.2.1 on 2024-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_productitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='limited_number_of_items_threshold',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
