# Generated by Django 4.2.1 on 2024-09-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_productitem_limited_number_of_items_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.ImageField(blank=True, default='icons/placeholder.jpg', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='limited_number_of_items_threshold',
            field=models.PositiveIntegerField(default=3, help_text='below and including this number number of items"'),
        ),
    ]
