# Generated by Django 4.2.1 on 2025-02-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_category_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
