# Generated by Django 4.2.1 on 2025-02-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_productitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='sku',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
