# Generated by Django 4.2.1 on 2025-02-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_alter_productitem_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='discount',
        ),
    ]
