# Generated by Django 4.2.1 on 2025-02-21 19:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0050_alter_featureditem_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='product',
            new_name='product_item',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product_item')},
        ),
    ]
