# Generated by Django 4.2.1 on 2025-02-21 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0051_rename_product_favorite_product_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='FavoriteProductItem',
        ),
    ]
