# Generated by Django 4.2.1 on 2025-03-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='product_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='products.productitem'),
        ),
    ]
