# Generated by Django 4.2.1 on 2025-03-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_alter_productdetails_product_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='ProductDetail',
        ),
    ]
