# Generated by Django 4.2.1 on 2025-03-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_rename_productdetails_productdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
