# Generated by Django 4.2.1 on 2025-03-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_tag_productitem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='generate_tags',
            field=models.BooleanField(default=False, help_text='this will gather info about the product and will try to create assosiated tags'),
        ),
    ]
