# Generated by Django 4.2.1 on 2025-03-24 19:11

from django.db import migrations
import uuid

def getn_uuid(apps, schema_editor):
    MyModel = apps.get_model("products", "ProductItem")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_productitem_uuid'),
    ]

    operations = [
        migrations.RunPython(getn_uuid, reverse_code=migrations.RunPython.noop)
    ]
