# Generated by Django 4.2.1 on 2025-03-24 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
