# Generated by Django 4.2.1 on 2025-06-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0061_remove_null_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='remove_background',
            field=models.BooleanField(default=False, help_text='removes the bg of the image, to revert you need to reupload the image!'),
        ),
    ]
