# Generated by Django 4.2.1 on 2025-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_rating_is_verified'),
        ('products', '0062_alter_productimage_remove_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='aspects',
            field=models.ManyToManyField(related_name='categories', to='ratings.ratingaspect'),
        ),
        migrations.AddField(
            model_name='product',
            name='override_aspects',
            field=models.ManyToManyField(related_name='products', to='ratings.ratingaspect'),
        ),
    ]
