# Generated by Django 4.2.1 on 2025-07-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_category_aspects_product_override_aspects'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_override_aspects',
            field=models.BooleanField(default=False),
        ),
    ]
