# Generated by Django 4.2.1 on 2025-07-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_aspectgroup'),
        ('products', '0064_product_use_override_aspects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='aspects',
        ),
        migrations.RemoveField(
            model_name='product',
            name='override_aspects',
        ),
        migrations.AddField(
            model_name='category',
            name='rating_aspects_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='ratings.aspectgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_aspects_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ratings.aspectgroup'),
        ),
    ]
