# Generated by Django 4.2.23 on 2025-08-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_alter_promotion_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='is_active',
            new_name='date_override',
        ),
    ]
