# Generated by Django 4.2.1 on 2023-07-16 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation_optional_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('variation_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variations.variationoptions')),
            ],
        ),
    ]
