# Generated by Django 4.2.1 on 2023-07-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_variation_optional_field'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation_optional_field',
            new_name='VariationOptionalField',
        ),
    ]
