# Generated by Django 4.2.1 on 2023-07-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0003_rename_variation_optional_field_variationoptionalfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': '1 Variations'},
        ),
        migrations.AlterModelOptions(
            name='variationoptionalfield',
            options={'verbose_name': 'Variation Extra Parameters', 'verbose_name_plural': '3. Variation extra Parameters'},
        ),
        migrations.AlterModelOptions(
            name='variationoptions',
            options={'verbose_name': 'Variation Values', 'verbose_name_plural': '2. Variation Values'},
        ),
        migrations.AlterField(
            model_name='variationoptionalfield',
            name='variation_option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_extra_parameters', to='variations.variationoptions'),
        ),
        migrations.AlterField(
            model_name='variationoptions',
            name='variation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variation_values', to='variations.variation'),
        ),
    ]
