# Generated by Django 4.2.1 on 2024-09-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0005_product_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationoptions',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
