import React from 'react'


const About = () => {
  return (
    <div>
      <blockquote>
        this is the new 
      </blockquote>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      <br />

      <h1>the second par of mar</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      <br />
      <section>
        <h2>this is the third par of mar</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
        <br />
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      </section>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      <br />
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis impedit, soluta numquam facilis culpa possimus? Sit maiores doloribus quas reiciendis ullam cupiditate perspiciatis voluptate? In libero reiciendis ipsam sunt itaque! Quam sed voluptatum id, quae eaque saepe, et, fuga neque blanditiis illum nobis maiores enim. Itaque minima rem officiis eius quibusdam? Id pariatur sit dolorum eveniet. Repellendus earum recusandae magnam ex repudiandae quia provident! Fuga omnis optio eligendi voluptates at consequuntur, corrupti minus totam autem beatae facilis, vel, quibusdam nemo esse nostrum culpa ex dolores dolorum voluptate! Voluptatem, distinctio doloremque, nemo repellat corrupti, quos minima quisquam natus quod laborum quidem.</p>
      <br />
      
    </div>
  )
}

export default About