export {default as Home} from './Home';
export {default as About} from './About'
export {default as Categories} from './Categories/Categories'
export {default as Contact} from './Contact'
export {default as Account} from './Account'
export {default as Settings} from './Settings/Settings'
export { Login } from './AuthPage/Login'
export { Register } from './AuthPage/Register/Register'
export { Profile } from './Profile/Profile'
export { ErrorPage } from './ErrorPage/ErrorPage';
export { LandingPage } from './LandingPage/LandingPage';
export { ProductDetail } from './ProductDetail/ProductDetail';
export { CartModal } from './Cart/CartModal'
export { Cart } from './Cart/Cart'
export { DeliveryTerms } from './DeliveryTerms/DeliveryTerms'
export { TermsOfUse } from './TermsOfUse/TermsOfUse'
export { Checkout } from './Checkout/Checkout';
export { Activation } from './Activation/Activation';
export { ActivationSuccess } from './Activation/ActivationSuccess'
export { Orders } from './Orders/Orders';
export { ShippingCosts } from './Checkout/ShippingCosts/ShippingCosts'
export { OrderSuccess } from './Orders/OrderSuccess/OrderSuccess';
export { RatingsCreate } from './Ratings/RatingsCreate/RatingsCreate';
