export {default as Home} from './Home';
export {default as About} from './About'
export {default as Categories} from './Categories/Categories'
export {default as Contact} from './Contact'
export {default as Account} from './Account'
export {default as Settings} from './Settings/Settings'
export { ProductsPage } from './ProductsPage';
export { Login } from './LoginPage/Login'
export { SignUp } from './SignUp/SignUp';
export { Profile } from './Profile/Profile'
export { ErrorPage } from './ErrorPage/ErrorPage';
export { LandingPage } from './LandingPage/LandingPage';
export { ProductDetail } from './ProductDetail/ProductDetail';
export { CartModal } from './Cart/CartModal'
export { Cart } from './Cart/Cart'
export { DeliveryTerms } from './DeliveryTerms/DeliveryTerms'
export { TermsOfUse } from './TermsOfUse/TermsOfUse'
export { Checkout } from './Checkout/Checkout';
