version: "3"

services:
  products_for_you:
    container_name: products_for_you
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin123"
      PGDATA: /data/products_for_you
    volumes:
      - products_for_you:/data/products_for_you
    ports:
      - "5433:5432"
    networks:
      - products_for_you_net
    restart: unless-stopped

networks:
  products_for_you_net:
    driver: bridge

volumes:
  products_for_you:
