version: "3"

services:
  products_for_you:
    container_name: products_for_you
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin123"
      PGDATA: /data/products_for_you
    volumes:
      - products_for_you:/data/products_for_you
    ports:
      - "5433:5432"
    networks:
      - products_for_you_net
    restart: unless-stopped
  e_search:
    container_name: product_for_you_elastic_2
    image: elasticsearch:7.17.22
    environment:
      - cluster.name=elastic-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      #      - xpack.monitoring.enabled=false
      - ELASTIC_USERNAME=test_elastic
      - ELASTIC_PASSWORD=elastic1234
      - "ES_JAVA_OPTS=-Xms4G -Xmx4G"
      - network.bind_host=0.0.0.0
    ports:
      - "9200:9200"
    networks:
      - products_for_you_net
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped
    depends_on:
      - products_for_you
networks:
  products_for_you_net:
    driver: bridge

volumes:
  products_for_you:
  elasticsearch-data:
    driver: local
