# Generated by Django 4.2.1 on 2025-03-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_created_at_stock_modified_at_store_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_details', to='inventory.store')),
            ],
        ),
    ]
