# Generated by Django 4.2.1 on 2025-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_storedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_default',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
