# Generated by Django 4.2.1 on 2023-06-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0002_customuser_date_joined_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='last_name',
        ),
    ]
