# Generated by Django 4.2.1 on 2023-11-24 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_control.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_remove_customuser_user_detail_delete_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('address_one', models.CharField(blank=True, default='', max_length=255)),
                ('address_two', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, default=user_control.models.get_default_user_image, max_length=255, null=True, upload_to=user_control.models.get_user_image)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
