# Generated by Django 4.2.1 on 2023-11-24 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0006_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 24, 22, 57, 30, 37952, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
