# Generated by Django 4.2.1 on 2024-10-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0008_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='cell_phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
