# Generated by Django 4.2.1 on 2025-03-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0009_userdetail_cell_phone_number_userdetail_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
