# Generated by Django 4.2.1 on 2025-04-04 17:09
from django.db import models, migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0013_populate_uuid_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
