# Generated by Django 4.2.1 on 2025-06-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0014_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('assistant', 'assistant'), ('editor', 'editor'), ('sales_person', 'sales_person'), ('customer', 'customer'), ('visitor', 'visitor'), ('demo_user', 'demo_user')], max_length=20),
        ),
    ]
