# Generated by Django 4.2.1 on 2025-07-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_adminresponse_comment_adminresponse_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingscore',
            name='aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='ratings.ratingaspect'),
        ),
    ]
