# Generated by Django 4.2.1 on 2025-07-21 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_alter_productimage_remove_background'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0003_alter_ratingscore_aspect'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'product')},
        ),
    ]
