# Generated by Django 4.2.1 on 2025-07-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
