# Generated by Django 4.2.1 on 2025-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_rating_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aspects', models.ManyToManyField(to='ratings.ratingaspect')),
            ],
        ),
    ]
