# Generated by Django 4.2.1 on 2025-07-27 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_aspectgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingscore',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
