# Generated by Django 4.2.1 on 2024-01-15 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping_cart', '0003_rename_card_id_cartitem_cart_id_cart_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('PROSSESING', 'Prossesing'), ('COMPLETED', 'Completed')], default='PROSSESING')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True)),
                ('order_date', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('phoneNumber', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=255)),
                ('billing_address', models.CharField(max_length=255)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('refund_status', models.CharField(choices=[('fl', 'False'), ('rq', 'requested'), ('cmpl', 'completed')], default='fl')),
                ('cartItems', models.ManyToManyField(related_name='orders', to='shopping_cart.cartitem')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
