# Generated by Django 4.2.1 on 2024-01-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productitem_variation_name'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporder',
            name='cartItems',
        ),
        migrations.AddField(
            model_name='shoporder',
            name='products',
            field=models.ManyToManyField(related_name='order_products', to='products.productitem'),
        ),
    ]
