# Generated by Django 4.2.1 on 2024-01-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_shoporder_cartitems_shoporder_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='modified',
            field=models.DateTimeField(blank=True),
        ),
    ]
