# Generated by Django 4.2.1 on 2024-01-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_shoporder_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus'),
        ),
    ]
