# Generated by Django 4.2.1 on 2024-01-15 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_productitem_variation_name'),
        ('order', '0004_alter_shoporder_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='order.shoporder')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productitem')),
            ],
        ),
    ]
