# Generated by Django 4.2.1 on 2024-01-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_shoporderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporder',
            name='products',
        ),
    ]
