# Generated by Django 4.2.1 on 2024-01-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_shoporder_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('PROSSESING', 'Prossesing'), ('COMPLETED', 'Completed')], default='PLACED'),
        ),
        migrations.AlterField(
            model_name='shoporder',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus'),
        ),
    ]
