# Generated by Django 4.2.1 on 2024-01-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_shoporder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderstatus'),
        ),
    ]
