# Generated by Django 4.2.1 on 2025-03-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_cart_locked'),
        ('payments', '0023_alter_shippingplan_company'),
        ('order', '0010_alter_shoporder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopping_cart.cart'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='shipping_method',
            field=models.CharField(choices=[('P', 'pick-up'), ('D', 'delivery')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='shipping_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.shippingplanoption'),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='stripe_payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
