# Generated by Django 4.2.1 on 2025-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_shoporder_cart_shoporder_shipping_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='session_cart',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
