# Generated by Django 4.2.1 on 2025-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_shoporder_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='extra_shipping_details',
            field=models.TextField(default='i want the item'),
            preserve_default=False,
        ),
    ]
