# Generated by Django 4.2.1 on 2025-04-03 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_shoporder_extra_shipping_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoporder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
