# Generated by Django 4.2.1 on 2025-04-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_shoporder_created_at_shoporder_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoporder',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='shoporder',
            name='order_date',
        ),
    ]
