# Generated by Django 4.2.1 on 2025-04-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_shoporder_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='extra_shipping_details',
            field=models.TextField(blank=True),
        ),
    ]
