# Generated by Django 4.2.1 on 2025-03-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcost',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shippingcost',
            name='volume_threshold',
            field=models.DecimalField(decimal_places=2, help_text='in grams the upper limit', max_digits=6, null=True),
        ),
    ]
