# Generated by Django 4.2.1 on 2025-03-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_shippingcost_title_shippingcost_volume_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcost',
            name='volume_threshold',
            field=models.DecimalField(decimal_places=2, help_text='in grams the upper limit', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='percentage', max_digits=4),
        ),
    ]
