# Generated by Django 4.2.1 on 2025-03-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_shippingcost_volume_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
