# Generated by Django 4.2.1 on 2025-03-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_location_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_country',
            field=models.BooleanField(default=False, help_text='is used for the client to fetch the list of available countries'),
        ),
    ]
