# Generated by Django 4.2.1 on 2025-03-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_location_is_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('value', models.DecimalField(decimal_places=2, help_text='the dimensional factor in cm', max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='shippingcost',
            name='volume_threshold',
            field=models.DecimalField(decimal_places=2, help_text='cubic meters upper limit', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shippingcost',
            name='dimensional_factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.dimensionalfactor'),
        ),
    ]
