# Generated by Django 4.2.1 on 2025-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_dimensionalfactor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionalfactor',
            name='type',
            field=models.CharField(default='standard', max_length=70),
            preserve_default=False,
        ),
    ]
