# Generated by Django 4.2.1 on 2025-03-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_dimensionalfactor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionalfactor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.location'),
        ),
    ]
