# Generated by Django 4.2.1 on 2025-03-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_dimensionalfactor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcost',
            name='volume_threshold',
            field=models.DecimalField(decimal_places=4, help_text='cubic meters upper limit', max_digits=8, null=True),
        ),
    ]
