# Generated by Django 4.2.1 on 2025-03-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_shippingcost_volume_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_threshold', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('volume_threshold', models.DecimalField(decimal_places=4, help_text='cubic meters upper limit', max_digits=8, null=True)),
                ('extra_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='payments.location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='payments.location')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='standard express etc', max_length=255)),
                ('pricing_strategy', models.CharField(choices=[('W', 'Weight'), ('D', 'Dimensional Weight')], help_text='charging strategy', max_length=1)),
                ('dimensional_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='payments.company')),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingcost',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='shippingcost',
            name='dimensional_factor',
        ),
        migrations.RemoveField(
            model_name='shippingcost',
            name='origin',
        ),
        migrations.DeleteModel(
            name='DimensionalFactor',
        ),
        migrations.DeleteModel(
            name='ShippingCost',
        ),
        migrations.AddField(
            model_name='shippingoption',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_option', to='payments.shippingplan'),
        ),
    ]
