# Generated by Django 4.2.1 on 2025-03-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_company_shippingoption_shippingplan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingOption',
            new_name='ShippingPlanOption',
        ),
    ]
