# Generated by Django 4.2.1 on 2025-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_rename_shippingoption_shippingplanoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='abbreviation',
            field=models.CharField(default='ATH', help_text='abbreviation like (e.g., ATH for Athens)', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
