# Generated by Django 4.2.1 on 2025-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_location_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingplan',
            name='base_cost',
        ),
        migrations.AddField(
            model_name='shippingplanoption',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
