# Generated by Django 4.2.1 on 2025-03-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_remove_shippingplan_base_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingplanoption',
            name='extra_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
