# Generated by Django 4.2.1 on 2025-03-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_shippingplanoption_extra_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingplanoption',
            name='weight_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
