# Generated by Django 4.2.1 on 2025-03-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_shippingplanoption_weight_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingplanoption',
            name='weight_threshold',
        ),
        migrations.AddField(
            model_name='shippingplanoption',
            name='max_weight_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='exclusive', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shippingplanoption',
            name='min_weight_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='inclusive', max_digits=12, null=True),
        ),
    ]
