# Generated by Django 4.2.1 on 2025-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_shippingplanoption_weight_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingplanoption',
            name='estimated_delivery_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
