# Generated by Django 4.2.1 on 2025-03-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_shippingplanoption_estimated_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingplanoption',
            name='estimated_delivery_time',
        ),
        migrations.AddField(
            model_name='shippingplanoption',
            name='max_estimated_delivery_time',
            field=models.DurationField(blank=True, help_text='format [dd] [HH:MM:SS]', null=True),
        ),
        migrations.AddField(
            model_name='shippingplanoption',
            name='min_estimated_delivery_time',
            field=models.DurationField(blank=True, help_text='format [dd] [HH:MM:SS]', null=True),
        ),
    ]
