# Generated by Django 4.2.1 on 2025-03-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_remove_uuid_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingplan',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='payments.company'),
        ),
    ]
