# Generated by Django 4.2.1 on 2025-03-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_shippingplan_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingplan',
            name='pricing_strategy',
            field=models.CharField(blank=True, choices=[('W', 'Weight'), ('D', 'Dimensional Weight')], help_text='charging strategy', max_length=1),
        ),
    ]
