# Generated by Django 4.2.1 on 2023-11-24 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
