# Generated by Django 4.2.1 on 2025-03-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_alter_cart_user_id_alter_cartitem_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
