# Generated by Django 4.2.1 on 2025-03-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_rename_user_id_cart_user_remove_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='completed',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('A', 'active'), ('AB', 'abandoned'), ('O', 'ordered')], default='A', max_length=2),
        ),
    ]
