# Generated by Django 4.2.1 on 2025-04-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_cart_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
